project:
  type: website
website:
  title: "Scuola di Specializzazione in Malattie Infettive e Tropicali"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - lecture1.qmd
      - lecture2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

